import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Contact from "./contact/page";
import About from "./about/page";
import {Inter, Roboto, Poppins} from "next/font/google"
import Navbar from "@/Components/navbar/Navbar";
import Footer from "@/Components/Footer/Footer";

const inter =Inter({ subsets: ["latin"]});
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body 
        className= {inter.className}>
          <div className="container">
                 <Navbar />
        {children}
        <Footer />
        </div>
      </body>
    </html>
  );
}
